# Generated by Django 5.0.3 on 2024-03-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todolist_priority_todolist_tags_alter_tags_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.todolist'),
        ),
    ]
