# Generated by Django 5.0.3 on 2024-03-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_todolist_tags_tags_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='list_id',
        ),
        migrations.AddField(
            model_name='todolist',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tags'),
        ),
    ]
