# Generated by Django 5.0.3 on 2024-03-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tags_list_id_todolist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='api.tags'),
        ),
    ]
