# Generated by Django 5.0.3 on 2024-03-29 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_todolist_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 29)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
        ),
    ]
